### ISSUE TITLE
Embed pschool on our website

### ISSUE THREAD

**Issue by rushishah07** [pschool-in/primary-school#2]
Hey, i loved the features you guys are providing for children and it will greatly help them to learn things quickly. My doubt was that I'm creating a website for school children, so is there a way by which i can embed your functionalities in my website? Or maybe i can embed your page into one section of my website? @pschool-in

**Comment by rethna2** [comment]
@rushishah07 , we are working on a feature where bloggers like you can embed the app in an iframe.  We are working on our backend. It will be ready sometime next week. 
You can create activities, and there will be unique url for each activities (www.pschool.in/<activity_id>) and you can embed them in an iframe.
Kindly share your blog url. (Either here or email to info@pschool.in)
